// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79l8giFL0GJXlGWgW6HM_awtusaHzOfc',
    appId: '1:550646316094:web:68c49f10d6f5e37193656f',
    messagingSenderId: '550646316094',
    projectId: 'elearnng-v2',
    authDomain: 'elearnng-v2.firebaseapp.com',
    storageBucket: 'elearnng-v2.firebasestorage.app',
    measurementId: 'G-K160F57KF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmWLgpefnOL72mo4nR9zvnxuSr2HFOM8',
    appId: '1:550646316094:android:aa3812d32adfb8cb93656f',
    messagingSenderId: '550646316094',
    projectId: 'elearnng-v2',
    storageBucket: 'elearnng-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoIC7JESQXGYXaPh49XzUJtADe6YmHL7o',
    appId: '1:550646316094:ios:2c76460753699bfe93656f',
    messagingSenderId: '550646316094',
    projectId: 'elearnng-v2',
    storageBucket: 'elearnng-v2.firebasestorage.app',
    iosClientId: '550646316094-2c1su1sqli8766df2fnk96pls4nf5gh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearningfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoIC7JESQXGYXaPh49XzUJtADe6YmHL7o',
    appId: '1:550646316094:ios:2c76460753699bfe93656f',
    messagingSenderId: '550646316094',
    projectId: 'elearnng-v2',
    storageBucket: 'elearnng-v2.firebasestorage.app',
    iosClientId: '550646316094-2c1su1sqli8766df2fnk96pls4nf5gh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearningfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79l8giFL0GJXlGWgW6HM_awtusaHzOfc',
    appId: '1:550646316094:web:f31f781e7749525493656f',
    messagingSenderId: '550646316094',
    projectId: 'elearnng-v2',
    authDomain: 'elearnng-v2.firebaseapp.com',
    storageBucket: 'elearnng-v2.firebasestorage.app',
    measurementId: 'G-D38X3993FD',
  );
}
