// Stub file for DefaultFirebaseOptions.
// Normally this file is generated by the FlutterFire CLI when you run:
//   flutterfire configure
// That command will create a `DefaultFirebaseOptions` class with a
// `currentPlatform` getter returning the correct `FirebaseOptions` for
// each platform (Android, iOS, web, etc.).
//
// If you haven't run `flutterfire configure`, keep this stub in place so
// the app gives a clear error message explaining what to do.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured.\n'
      'Run `flutterfire configure` to generate `lib/firebase_options.dart`\n'
      'or replace this stub with your own FirebaseOptions.\n'
      'See README for detailed steps.'
    );
  }
}
